//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int SellId { get; set; }
        public int ProductPlanId { get; set; }
        public int ProductQuantity { get; set; }
        public int TotalAmount { get; set; }
        public int EmployeeId { get; set; }
        public int clientid { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ProductPlan ProductPlan { get; set; }
    }
}
