//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int StorageId { get; set; }
        public int ProductPlanId { get; set; }
        public int ProductQuantity { get; set; }
        public System.DateTime ProductExpireDate { get; set; }
    
        public virtual ProductPlan ProductPlan { get; set; }
    }
}
